version: '3'

services:
###> doctrine/doctrine-bundle ###
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: api-platform-jobs-mysql
    ports:
        - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: '${DB_DATABASE:-api}'
        MYSQL_USER: '${DB_USERNAME:-symfony}'
        MYSQL_PASSWORD: '${DB_PASSWORD:-symfony}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - ./init:/docker-entrypoint-initdb.d
        # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
        # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
        - api-platform-jobs
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-symfony}"]
        retries: 3
        timeout: 5s

  phpmyadmin:
    image: phpmyadmin
    container_name: api-platform-jobs-phpmyadmin
    environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-api}'
    links:
        - mysql:mysql
    ports:
        - "8008:80"
    networks:
        - api-platform-jobs
    depends_on:
        - mysql
###< doctrine/doctrine-bundle ###

networks:
    api-platform-jobs:
        driver: bridge
# volumes:
###> doctrine/doctrine-bundle ###
  # database_data:
###< doctrine/doctrine-bundle ###
